In [1]:
print('hello world')

hello world


In [4]:
import numpy as np


# x = np.array([5,15,25,35])

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
# b = a.reshape(2,6)
# c = a.reshape(6,2)
# print(b.ndim)
# print(c.ndim)


ModuleNotFoundError: No module named 'numpy'

In [5]:
pip install numpy

     ---------------------------------------- 14.6/14.6 MB 5.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np


# x = np.array([5,15,25,35])

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [2]:
import numpy as np


# x = np.array([5,15,25,35])

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
# b = a.reshape(2,6)
# c = a.reshape(6,2)
# print(b.ndim)
# print(c.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
import numpy as np


# x = np.array([5,15,25,35])

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
b = a.reshape(2,6)
c = a.reshape(6,2)
print(b.ndim)
print(c.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
2
2


In [4]:
import numpy as np


# x = np.array([5,15,25,35])

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
# b = a.reshape(2,6)
# c = a.reshape(6,2)
# print(b.ndim)
# print(c.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

# Load the dataset
data = pd.read_csv("C:\\Users\\Enes Jashari\\Desktop\\RS1.L.csv")

# Dependent variable Y
close_prices = data['Close']

#Open + Volume = independent variables X
data2 = np.genfromtxt("C:\\Users\\Enes Jashari\\Desktop\\RS1.L.csv", dtype='float', delimiter=',', skip_header=1, usecols=(1,6))

X = np.array(data2)
print(X)

# Split the data into training/testing sets
X_train = np.array(X[:450]).reshape((-1, 2)) #we take the first 450 elements
X_test = np.array(X[450:]).reshape((-1, 2)) #we take elements after 450 index

# Split the targets into training/testing sets
Y_train = close_prices[:450] #we take the first 450 elements
Y_test = close_prices[450:] #we take elements after 450 index

regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(Y_test, Y_pred))


ModuleNotFoundError: No module named 'matplotlib'

In [3]:
pip install matplotlib



     ---------------------------------------- 7.2/7.2 MB 3.4 MB/s eta 0:00:00
     -------------------------------------- 164.1/164.1 kB 2.0 MB/s eta 0:00:00
     -------------------------------------- 960.8/960.8 kB 4.1 MB/s eta 0:00:00
  Using cached Pillow-9.2.0-cp310-cp310-win_amd64.whl (3.3 MB)
     -------------------------------------- 55.3/55.3 kB 714.6 kB/s eta 0:00:00


In [4]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install pandas 

     ---------------------------------------- 10.4/10.4 MB 5.3 MB/s eta 0:00:00
     -------------------------------------- 500.8/500.8 kB 4.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [1]:
print('hello world')

hello world


In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

# Load the dataset
data = pd.read_csv("C:\\Users\\Enes Jashari\\Desktop\\RS1.L.csv")

# Dependent variable Y
close_prices = data['Close']

#Open + Volume = independent variables X
data2 = np.genfromtxt("C:\\Users\\Enes Jashari\\Desktop\\RS1.L.csv", dtype='float', delimiter=',', skip_header=1, usecols=(1,6))

X = np.array(data2)
print(X)

# Split the data into training/testing sets
X_train = np.array(X[:450]).reshape((-1, 2)) #we take the first 450 elements
X_test = np.array(X[450:]).reshape((-1, 2)) #we take elements after 450 index

# Split the targets into training/testing sets
Y_train = close_prices[:450] #we take the first 450 elements
Y_test = close_prices[450:] #we take elements after 450 index

regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(Y_test, Y_pred))

Matplotlib is building the font cache; this may take a moment.


ModuleNotFoundError: No module named 'sklearn'

In [3]:
pip install sklearn

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 7.4/7.4 MB 4.7 MB/s eta 0:00:00
     ---------------------------------------- 38.6/38.6 MB 4.2 MB/s eta 0:00:00
     -------------------------------------- 298.0/298.0 kB 3.1 MB/s eta 0:00:00
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1304 sha256=bb205cdd0a24c32c4f2ccaef50913f677b3ed9c0b163020d504461e9fe2dbced
  Stored in directory: c:\users\enes jashari\appdata\local\pip\cache\wheels\9b\13\01\6f3a7fd641f90e1f6c8c7cded057f3394f451f340371c68f3d
Successfully built sklearn
Note: you may need to restart the kernel to use updated packages.


In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

# Load the dataset
data = pd.read_csv("C:\\Users\\Enes Jashari\\Desktop\\RS1.L.csv")

# Dependent variable Y
close_prices = data['Close']

#Open + Volume = independent variables X
data2 = np.genfromtxt("C:\\Users\\Enes Jashari\\Desktop\\RS1.L.csv", dtype='float', delimiter=',', skip_header=1, usecols=(1,6))

X = np.array(data2)
print(X)

# Split the data into training/testing sets
X_train = np.array(X[:450]).reshape((-1, 2)) #we take the first 450 elements
X_test = np.array(X[450:]).reshape((-1, 2)) #we take elements after 450 index

# Split the targets into training/testing sets
Y_train = close_prices[:450] #we take the first 450 elements
Y_test = close_prices[450:] #we take elements after 450 index

regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(Y_test, Y_pred))

[[1.76600006e+02 3.91712000e+05]
 [1.72600006e+02 5.25209000e+05]
 [1.75899994e+02 6.51939000e+05]
 ...
 [9.91000000e+02 1.58246900e+06]
 [9.94000000e+02 1.37135500e+06]
 [1.01200000e+03 1.00432100e+06]]
Coefficients: 
 [9.95480055e-01 1.60000661e-06]
Mean squared error: 200.39
Coefficient of determination: 0.99


In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

# Load the dataset
data = pd.read_csv("C:\\Users\\Enes Jashari\\Desktop\\TSLA.csv")

# Dependent variable Y
close_prices = data['Close']

#Open + Volume = independent variables X
data2 = np.genfromtxt("C:\\Users\\Enes Jashari\\Desktop\\TSLA.csv", dtype='float', delimiter=',', skip_header=1, usecols=(1,6))

X = np.array(data2)
print(X)

# Split the data into training/testing sets
X_train = np.array(X[:450]).reshape((-1, 2)) #we take the first 450 elements
X_test = np.array(X[450:]).reshape((-1, 2)) #we take elements after 450 index

# Split the targets into training/testing sets
Y_train = close_prices[:450] #we take the first 450 elements
Y_test = close_prices[450:] #we take elements after 450 index

regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(Y_test, Y_pred))

[[2.65500000e+02 9.14499000e+07]
 [2.61600006e+02 5.52978000e+07]
 [2.58733337e+02 4.38984000e+07]
 [2.61820007e+02 5.75874000e+07]
 [2.65403320e+02 5.02158000e+07]
 [2.62549988e+02 4.26009000e+07]
 [2.66976654e+02 6.60600000e+07]
 [2.70156677e+02 4.23603000e+07]
 [2.71829987e+02 3.67416000e+07]
 [2.74579987e+02 5.67738000e+07]
 [2.83929993e+02 7.26216000e+07]
 [2.92510010e+02 5.21433000e+07]
 [2.88450012e+02 4.20963000e+07]
 [2.85333344e+02 9.44445000e+07]
 [2.98500000e+02 6.86424000e+07]
 [3.16843323e+02 1.88556300e+08]
 [3.41563324e+02 1.87245000e+08]
 [3.46553345e+02 1.15579500e+08]
 [3.56103333e+02 8.16396000e+07]
 [3.60619995e+02 8.97552000e+07]
 [3.81666656e+02 1.68146100e+08]
 [3.86453339e+02 1.28213400e+08]
 [3.92443329e+02 1.03885500e+08]
 [4.11470001e+02 7.61922000e+07]
 [4.09333344e+02 6.48864000e+07]
 [3.83263336e+02 1.00337100e+08]
 [3.91200012e+02 1.77317400e+08]
 [3.36803345e+02 1.28408100e+08]
 [3.67589996e+02 6.71898000e+07]
 [3.49166656e+02 7.67193000e+07]
 [3.392099

ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by LinearRegression.

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

# Load the dataset
data = pd.read_csv("C:\\Users\\Enes Jashari\\Desktop\\TSLA.csv")

# Dependent variable Y
close_prices = data['Close']

#Open + Volume = independent variables X
data2 = np.genfromtxt("C:\\Users\\Enes Jashari\\Desktop\\TSLA.csv", dtype='float', delimiter=',', skip_header=1, usecols=(1,6))

X = np.array(data2)
print(X)

# Split the data into training/testing sets
X_train = np.array(X[:450]).reshape((-1, 2)) #we take the first 450 elements
X_test = np.array(X[450:]).reshape((-1, 2)) #we take elements after 450 index

# Split the targets into training/testing sets
Y_train = close_prices[:450] #we take the first 450 elements
Y_test = close_prices[450:] #we take elements after 450 index

regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(Y_test, Y_pred))

[[2.65500000e+02 9.14499000e+07]
 [2.61600006e+02 5.52978000e+07]
 [2.58733337e+02 4.38984000e+07]
 [2.61820007e+02 5.75874000e+07]
 [2.65403320e+02 5.02158000e+07]
 [2.62549988e+02 4.26009000e+07]
 [2.66976654e+02 6.60600000e+07]
 [2.70156677e+02 4.23603000e+07]
 [2.71829987e+02 3.67416000e+07]
 [2.74579987e+02 5.67738000e+07]
 [2.83929993e+02 7.26216000e+07]
 [2.92510010e+02 5.21433000e+07]
 [2.88450012e+02 4.20963000e+07]
 [2.85333344e+02 9.44445000e+07]
 [2.98500000e+02 6.86424000e+07]
 [3.16843323e+02 1.88556300e+08]
 [3.41563324e+02 1.87245000e+08]
 [3.46553345e+02 1.15579500e+08]
 [3.56103333e+02 8.16396000e+07]
 [3.60619995e+02 8.97552000e+07]
 [3.81666656e+02 1.68146100e+08]
 [3.86453339e+02 1.28213400e+08]
 [3.92443329e+02 1.03885500e+08]
 [4.11470001e+02 7.61922000e+07]
 [4.09333344e+02 6.48864000e+07]
 [3.83263336e+02 1.00337100e+08]
 [3.91200012e+02 1.77317400e+08]
 [3.36803345e+02 1.28408100e+08]
 [3.67589996e+02 6.71898000e+07]
 [3.49166656e+02 7.67193000e+07]
 [3.392099

ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by LinearRegression.

In [9]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

# Load the dataset
data = pd.read_csv("C:\\Users\\Enes Jashari\\Downloads\\ETH-USD.csv")

# Dependent variable Y
close_prices = data['Close']

#Open + Volume = independent variables X
data2 = np.genfromtxt("C:\\Users\\Enes Jashari\\Downloads\\ETH-USD.csv", dtype='float', delimiter=',', skip_header=1, usecols=(5,6))

X = np.array(data2)
print(X)

# Split the data into training/testing sets
X_train = np.array(X[:450]).reshape((-1, 2)) #we take the first 450 elements
X_test = np.array(X[450:]).reshape((-1, 2)) #we take elements after 450 index

# Split the targets into training/testing sets
Y_train = close_prices[:450] #we take the first 450 elements
Y_test = close_prices[450:] #we take elements after 450 index

regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(Y_test, Y_pred))

[[1.54581940e+02 3.12619254e+09]
 [1.55638596e+02 3.33821193e+09]
 [1.57746201e+02 3.23129437e+09]
 ...
 [1.31164441e+03 6.22796124e+09]
 [1.27609351e+03 7.57835165e+09]
 [1.30074255e+03 9.06552115e+09]]
Coefficients: 
 [ 1.00000000e+00 -1.25367859e-24]
Mean squared error: 0.00
Coefficient of determination: 1.00


In [10]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

# Load the dataset
data = pd.read_csv("C:\\Users\\Enes Jashari\\Downloads\\ETH-USD.csv")

# Dependent variable Y
close_prices = data['Close']

#Open + Volume = independent variables X
data2 = np.genfromtxt("C:\\Users\\Enes Jashari\\Downloads\\ETH-USD.csv", dtype='float', delimiter=',', skip_header=1, usecols=(5,6))

X = np.array(data2)
print(X)

# Split the data into training/testing sets
X_train = np.array(X[:450]).reshape((-1, 2)) #we take the first 450 elements
X_test = np.array(X[450:]).reshape((-1, 2)) #we take elements after 450 index

# Split the targets into training/testing sets
Y_train = close_prices[:450] #we take the first 450 elements
Y_test = close_prices[450:] #we take elements after 450 index

regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(Y_test, Y_pred))

[[1.54581940e+02 3.12619254e+09]
 [1.55638596e+02 3.33821193e+09]
 [1.57746201e+02 3.23129437e+09]
 ...
 [1.31164441e+03 6.22796124e+09]
 [1.27609351e+03 7.57835165e+09]
 [1.30074255e+03 9.06552115e+09]]
Coefficients: 
 [ 1.00000000e+00 -1.25367859e-24]
Mean squared error: 0.00
Coefficient of determination: 1.00
